name: flutter_realistic_flipbook_example
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_realistic_flipbook:
    path: ..

flutter:
  uses-material-design: true
